In [42]:
import cv2
import mahotas 
import math
import numpy as np
centers = []
frame_count =0
cap = cv2.VideoCapture(r"C:\Users\aniru\Downloads\DIP_DRS\hotspot.mov")
fourcc = cv2.VideoWriter_fourcc(*'BA81')
output = np.zeros((1920, 1080))
print(cap.isOpened()) 
while(cap.isOpened()):
    ret, frame = cap.read()
    frame_count+=1
    if ret == True:
        center = mahotas.center_of_mass(frame) 
        if  not math.isnan(center[0]):
            print(center)
            centers.append(center) 
    if frame_count ==322 :
        break
    if cv2.waitKey(1) & 0xFF == ord('q'):
            break
    


cap.release()
cv2.destroyAllWindows()

True
[506.52950687  10.81926319   1.        ]
[535.68633008  70.79307936   1.00270235]
[654.49506903 249.99309665   1.        ]
[655. 248.   1.]
[730.43189756 363.94470314   1.        ]
[2.04862745e+01 1.80088235e+03 1.00000000e+00]
[791.43216236 467.36849696   1.        ]
[764.49668903 491.81449833   1.00305964]
[729.77432864 511.0107313    1.00099461]
[705.00800172 535.69367397   1.00148911]
[1.76250e+02 1.41775e+03 1.00000e+00]
[649.00556087 582.50540881   1.00173777]
[626.81323418 606.84759648   0.99942798]
[596.88221462 624.40808038   1.        ]
[577.64699878 653.39865251   1.00020416]
[543.71960298 681.45905707   0.96029777]
[530.79878472 698.94633172   0.998695  ]
[4.74531915e+02 8.50425532e+02 3.19148936e-01]
[487.35242634 744.1669844    0.99722704]
[474.60315671 770.93478449   0.99722487]
[4.74531915e+02 8.50425532e+02 3.19148936e-01]
[438.43517917 817.11524017   0.999407  ]
[4.74531915e+02 8.50425532e+02 3.19148936e-01]
[407.62732304 864.14246501   0.99856005]
[401.95879397 

[9.15793103e+02 1.37724138e+02 3.10344828e-01]
[9.15793103e+02 1.37724138e+02 3.10344828e-01]
[9.15793103e+02 1.37724138e+02 3.10344828e-01]
[9.15793103e+02 1.37724138e+02 3.10344828e-01]
[9.15793103e+02 1.37724138e+02 3.10344828e-01]
[9.15793103e+02 1.37724138e+02 3.10344828e-01]
[9.15793103e+02 1.37724138e+02 3.10344828e-01]
[9.15793103e+02 1.37724138e+02 3.10344828e-01]
[9.15793103e+02 1.37724138e+02 3.10344828e-01]
[9.15793103e+02 1.37724138e+02 3.10344828e-01]
[9.15793103e+02 1.37724138e+02 3.10344828e-01]
[9.15793103e+02 1.37724138e+02 3.10344828e-01]
[9.15793103e+02 1.37724138e+02 3.10344828e-01]
[9.15793103e+02 1.37724138e+02 3.10344828e-01]
[9.15793103e+02 1.37724138e+02 3.10344828e-01]
[9.15793103e+02 1.37724138e+02 3.10344828e-01]
[9.15793103e+02 1.37724138e+02 3.10344828e-01]
[9.15793103e+02 1.37724138e+02 3.10344828e-01]
[9.15793103e+02 1.37724138e+02 3.10344828e-01]
[9.15793103e+02 1.37724138e+02 3.10344828e-01]
[4.83765743e+01 1.74554030e+03 9.74811083e-01]
[9.15793103e+

In [43]:
centers[2]

array([654.49506903, 249.99309665,   1.        ])

In [21]:
conda install -c https://conda.anaconda.org/conda-forge mahotas

Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Anaconda\envs\tf

  added / updated specs:
    - mahotas


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2020.11.8  |       h5b45459_0         183 KB  conda-forge
    certifi-2020.11.8          |   py37h03978a9_0         150 KB  conda-forge
    mahotas-1.4.11             |   py37h08fd248_1         1.7 MB  conda-forge
    openssl-1.1.1h             |       he774522_0         5.8 MB  conda-forge

Note: you may need to restart the kernel to use updated packages.    ------------------------------------------------------------





==> WARNING: A newer version of conda exists. <==
  current version: 4.8.3
  latest version: 4.9.2

Please update conda by running

    $ conda update -n base -c defaults conda




                                           Total:         7.8 MB

The following NEW packages will be INSTALLED:

  mahotas            conda-forge/win-64::mahotas-1.4.11-py37h08fd248_1

The following packages will be UPDATED:

  ca-certificates    pkgs/main::ca-certificates-2020.7.22-0 --> conda-forge::ca-certificates-2020.11.8-h5b45459_0
  certifi               pkgs/main::certifi-2020.6.20-py37_0 --> conda-forge::certifi-2020.11.8-py37h03978a9_0

The following packages will be SUPERSEDED by a higher-priority channel:

  openssl                                         pkgs/main --> conda-forge




certifi-2020.11.8    | 150 KB    |            |   0% 
certifi-2020.11.8    | 150 KB    | #          |  11% 
certifi-2020.11.8    | 150 KB    | ########## | 100% 

ca-certificates-2020 | 183 KB    |            |   0% 
ca-certificates-2020 | 183 KB    | ########## | 100% 

openssl-1.1.1h       | 5.8 MB    |            |   0% 
openssl-1.1.1h       | 5.8 MB    | 8          |   8% 
openssl-1.1.1h  

In [47]:
images =[]
for c in centers :
    img = cv2.imread(r"C:\Users\aniru\Downloads\DIP_DRS\wp2945005.jpg")
    cv2.circle(img,(int(c[1]),int(c[0])),10,(255,255,255),-11)
    images.append(img)

In [48]:
out = cv2.VideoWriter('track.mov',cv2.VideoWriter_fourcc(*'BA81'), 60, (1920,1080))
 
for i in range(len(images)):
    out.write(images[i])
out.release()